#
# Copyright 2024, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

# TODO automate updating

[allow]
aarch64-cpu = "11.1.0"
ab_glyph = "0.2.32"
addr2line = "0.25.1"
aligned = "0.4.2"
anyhow = "1.0.100"
async-unsync = "0.3.0"
bindgen = "0.72.1"
bitfield = "0.19.3"
bytemuck = "1.24.0"
cc = "1.2.43"
cfg-if = "1.0.4"
chrono = "0.4.42"
clap = "4.5.50"
dlmalloc = "0.2.11"
embedded-hal-nb = "1.0"
embedded-io-async = "0.7.0"
env_logger = "0.11.8"
fallible-iterator = "0.3.0"
fdt = "0.1.5"
futures = "0.3.31"
getrandom = "0.2.10"
gimli = "0.32.3"
glob = "0.3.3"
gpt_disk_types = "0.16.1"
heapless = "0.9.1"
hex = "0.4.3"
httparse = "1.10.1"
lock_api = "0.4.14"
log = "0.4.28"
lru = "0.16.2"
miniz_oxide = "0.8.9"
num = "0.4.3"
num_enum = "0.7.5"
num-traits = "0.2.19"
object = "0.37.3"
one-shot-mutex = "0.2.1"
paste = "1.0.15"
pest = { version = "2.8.3", applies-to = ["pest", "pest_derive"] }
pin-project = "1.1.10"
postcard = "1.1.3"
prettyplease = "0.2.37"
proc-macro2 = "1.0.103"
ptr_meta = "0.3.1"
quote = "1.0.41"
rand = "0.9.2"
rcgen = "0.14.5"
regex = "1.12.2"
ring = "=0.17.8"
riscv = "0.15.0"
rsa = "0.9.8"
rtcc = "0.4.0"
rustls = "0.23.5"
rustls-pemfile = "2.0.0"
rustversion = "1.0.22"
sbi = "0.3.0"
serde = "1.0.228"
serde_json = "1.0.145"
serde_yaml = "0.9.34" # TODO depricated
smccc = "0.2.2"
smoltcp = "0.12.0"
spin = "0.10.0"
stable_deref_trait = "1.2.1" # for gimli dep of sel4-backtrace-addr2line-context-helper
syn = "2.0.108"
thiserror = "2.0.17"
tock-registers = "0.10.0"
unwinding = "0.2.8"
verus_builtin = "0.0.0-2025-08-12-1837"
verus_builtin_macros = "0.0.0-2025-08-12-1837"
virtio-drivers = "0.12.0"
vstd = "0.0.0-2025-08-12-1837"
webpki-roots = "1.0.3"
xmltree = "0.11.0"
zerocopy = "0.8.27"
